name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run Pytest
        run: |
          cd backend
          pytest test_main.py

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/carbon-backend
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker build -t $IMAGE_ID:latest ./backend
          docker push $IMAGE_ID:latest

      - name: Build and Push Frontend
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/carbon-frontend
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker build -t $IMAGE_ID:latest ./frontend
          docker push $IMAGE_ID:latest

      - name: Setup Minikube for Kubernetes Deployment
        uses: medyagh/setup-minikube@latest

      - name: Substitute GHCR Image Names in Manifests
        run: |
          IMAGE_ID_BACKEND=$(echo ghcr.io/${{ github.repository }}/carbon-backend:latest | tr '[A-Z]' '[a-z]')
          IMAGE_ID_FRONTEND=$(echo ghcr.io/${{ github.repository }}/carbon-frontend:latest | tr '[A-Z]' '[a-z]')
          sed -i "s|myacr.azurecr.io/carbon-backend:latest|$IMAGE_ID_BACKEND|g" k8s/backend.yaml
          sed -i "s|myacr.azurecr.io/carbon-frontned:latest|$IMAGE_ID_FRONTEND|g" k8s/frontend.yaml
          sed -i "s|myacr.azurecr.io/carbon-frontend:latest|$IMAGE_ID_FRONTEND|g" k8s/frontend.yaml

      - name: Run Ansible Playbook
        run: |
          sudo apt-get update && sudo apt-get install -y ansible
          ansible-galaxy collection install kubernetes.core
          ansible-playbook -i ansible/inventory ansible/deploy.yaml

      - name: Verify Deployment Success
        run: |
          kubectl get pods -n default
          kubectl get services -n default
